Enable Unknown GUIDs if requested
LittleBigRefresh/Refresh pull request #336
Opened 2024-01-07 16:41 UTC by Manoplay

If you have a modded game with custom GUIDs in the game files, especially as stickers, they won't be accepted by the server.
With this modification, you can change this behavior through configuration key  "EnableUnknownGuids".

2024-01-07 22:13 UTC, Beyley requested changes
Only minor nitpicks on naming and formatting, other than that this is a good change

2024-01-07 22:13 UTC, Beyley commented on Refresh.GameServer/Services/GuidCheckerService.cs
> +        if (this._config.EnableUnknownGuids) return true;
More bikeshedding, but i'd prefer if it was 
```suggestion
        // If specified in the config, allow all GUIDs
        if (this._config.EnableUnknownGuids) return true;
```

2024-01-07 22:13 UTC, Beyley commented on Refresh.GameServer/Configuration/GameServerConfig.cs
> +    public bool EnableUnknownGuids { get; set; } = false;
A bit of a bikeshed, but i'd prefer the name to be `AllowInvalidTextureGuids`
```suggestion
    public bool AllowInvalidTextureGuids { get; set; } = false;
```

2024-01-07 22:13 UTC, Beyley commented on Refresh.GameServer/Services/GuidCheckerService.cs
> +    internal GuidCheckerService( GameServerConfig config, Logger logger) : base(logger)
Small formatting fix
```suggestion
    internal GuidCheckerService(GameServerConfig config, Logger logger) : base(logger)
```

2024-01-08 00:57 UTC, Manoplay commented
I applied all the modifications requested

2024-01-08 01:19 UTC, Beyley approved these changes

2024-01-08 01:19 UTC, merged

2024-01-08 01:20 UTC, Beyley commented
Thank you for the contribution!