FindRoomMethod: Fix level ID search & always print room state
LittleBigRefresh/Refresh pull request #548
Opened 2024-06-30 22:53 UTC by Beyley

Printing the room state out always helps a lot with debugging when people state that "dive in doesn't work". 
Often by the time someone responds "can you take a capture of the API room output", the room state has changed enough where it's not as helpful, the API also doesn't expose info like NAT type or build version. This change makes sure that we can easily see exactly what the server was seeing when it filtered down the rooms, and can narrow down why no rooms were found.

If the extra noise does become a problem in the future when we grow and have many rooms, I have made the dump a config option, so that it can be easily disabled/re-enabled when needed.

The level ID search changes should also fix some issues people have been having with dive in.

2024-07-01 23:11 UTC, jvyden requested changes
looks fine, but `IMatchMethod` is getting messy:

2024-07-01 23:11 UTC, jvyden commented on Refresh.GameServer/Types/Matching/MatchMethods/IMatchMethod.cs
>  }
should use `DataContext`

2024-07-06 23:48 UTC, Beyley commented on Refresh.GameServer/Types/Matching/MatchMethods/IMatchMethod.cs
>  }
switched to using a data context

2024-07-09 22:26 UTC, jvyden approved these changes

2024-07-09 22:26 UTC, merged